### ISSUE TITLE
README file request

### ISSUE THREAD

**Issue by lhaippp** [RViMLab/MICCAI2023-Camera-Motion-Prediction#1]
Thanks for your excellent work, The topic(deep homography and endoscopy imaging) is really interesting!
By the way, I would like to ask whether you could provide a README file for the authors?

**Comment by mhubii** [comment]
hi @lhaippp , yes good point, let's add a readme

**Comment by mhubii** [comment]
there is now a readme, please let me know if this works for you. Sorry, but the code is a little messy and definitely needs some re-factoring. If you need help running inference for anything (for comparisons etc), please let me know and I'll help you out

**Comment by lhaippp** [comment]
Hi mhubii,
Thank you very much for your help! 
I'll try to run it first.

**Comment by lhaippp** [comment]
By the way, I am fascinated by the topic of "homography application in endoscopy imaging," as it is exactly in line with my primary research interests. 
I am currently reading your papers and code. If it's convenient for you, could I possibly have your email address? I would be very keen to engage in a more in-depth discussion regarding this field of research with you.

**Comment by mhubii** [comment]
See the problem is there are plenty hard-coded paths, data modules that require pre-processing of the open source datasets... 

This repository is unfortunately not very run-able at the moment.

However, configurations for the homography prediction on cholec80 are e.g. here https://github.com/RViMLab/MICCAI2023-Camera-Motion-Prediction/blob/main/config/homography_imitation/conv_homography_predictor_cholec80.yml

The [main](https://github.com/RViMLab/MICCAI2023-Camera-Motion-Prediction/blob/main/main_homography_imitation_seq.py) reads these configs and loads modules accordingly. I don't think this runs on someone else's machine out of the box
